# Generated by Django 4.2.2 on 2023-09-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_allergies_post_gender_post_medical_conditions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='block',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='houseNumber',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
