# Generated by Django 4.2.2 on 2023-09-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_post_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='latitude',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='longitude',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
