# Generated by Django 4.2.2 on 2024-03-12 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_post_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
    ]
