# Generated by Django 4.2.2 on 2023-08-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencycontact',
            name='name',
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='entity',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
