# Generated by Django 4.2.2 on 2023-08-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_contact', '0002_remove_emergencycontact_name_emergencycontact_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycontact',
            name='type',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
