# Generated by Django 4.2.2 on 2023-08-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_contact', '0004_emergency_delete_emergencycontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='contact',
            field=models.CharField(max_length=50),
        ),
    ]
