# Generated by Django 4.2.2 on 2024-01-02 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_rename_author_comment_authorname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='authorName',
            new_name='author',
        ),
    ]
